[hello_world]
parser-v1 = true

[hello_world.jobby]
message="Let's see"

[hello_world.otherjobby]
message="I'll check this one too"
consul_service_name = "otherjobby"

[democratic_csi_zol_iscsi]
_registry = "me"

[democratic_csi_zol_iscsi.iscsi]
datacenters = ["go-for-it"]
resources.cpu = 500
resources.memory = 256

[gokapi]

[gokapi.fileshare]
datacenters = ["dc1", "dc2"]
image_source = "f0rc3/gokapi"
image_version = "latest"
resoures = {cpu = 500, memory = 512}
